=== mariyaveleva16/XML/XML2022_ProjectNo8/unisInBG.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT universitiesBG (universityList,branchList,regionList)>
<!ATTLIST universitiesBG
  xmlns CDATA #FIXED ''
  xmlns:xsi CDATA #FIXED 'http://www.w3.org/2001/XMLSchema-instance'
  xsi:noNamespaceSchemaLocation NMTOKEN #REQUIRED>

<!ELEMENT universityList (university)+>
<!ATTLIST universityList xmlns CDATA #FIXED ''>

<!ELEMENT branchList (branch)+>
<!ATTLIST branchList xmlns CDATA #FIXED ''>

<!ELEMENT regionList (regionInfo)+>
<!ATTLIST regionList xmlns CDATA #FIXED ''>

<!ELEMENT university (universityInfo,facultyList)>
<!ATTLIST university xmlns CDATA #FIXED ''>

<!ELEMENT branch (seatName,universityRef)>
<!ATTLIST branch xmlns CDATA #FIXED ''>

<!ELEMENT regionInfo (regionName,regionRef)>
<!ATTLIST regionInfo xmlns CDATA #FIXED ''>

<!ELEMENT universityInfo (name,branchName?,location,region,id,regionId,
                          telephone,secondTelephone?,year,students?,img,
                          webSite?)>
<!ATTLIST universityInfo xmlns CDATA #FIXED ''>

<!ELEMENT facultyList (faculty)+>
<!ATTLIST facultyList xmlns CDATA #FIXED ''>

<!ELEMENT seatName (#PCDATA)>
<!ATTLIST seatName xmlns CDATA #FIXED ''>

<!ELEMENT universityRef EMPTY>
<!ATTLIST universityRef xmlns CDATA #FIXED '' idRef CDATA #REQUIRED nameRef CDATA #REQUIRED>

<!ELEMENT regionName (#PCDATA)>
<!ATTLIST regionName xmlns CDATA #FIXED ''>

<!ELEMENT regionRef EMPTY>
<!ATTLIST regionRef xmlns CDATA #FIXED '' regIdRef CDATA #REQUIRED regRef CDATA #REQUIRED>

<!ELEMENT name (#PCDATA)>
<!ATTLIST name xmlns CDATA #FIXED ''>

<!ELEMENT branchName (#PCDATA)>
<!ATTLIST branchName xmlns CDATA #FIXED ''>

<!ELEMENT location (#PCDATA)>
<!ATTLIST location xmlns CDATA #FIXED ''>

<!ELEMENT region (#PCDATA)>
<!ATTLIST region xmlns CDATA #FIXED ''>

<!ELEMENT id (#PCDATA)>
<!ATTLIST id xmlns CDATA #FIXED ''>

<!ELEMENT regionId (#PCDATA)>
<!ATTLIST regionId xmlns CDATA #FIXED ''>

<!ELEMENT telephone (#PCDATA)>
<!ATTLIST telephone xmlns CDATA #FIXED ''>

<!ELEMENT secondTelephone (#PCDATA)>
<!ATTLIST secondTelephone xmlns CDATA #FIXED ''>

<!ELEMENT year (#PCDATA)>
<!ATTLIST year xmlns CDATA #FIXED ''>

<!ELEMENT students (#PCDATA)>
<!ATTLIST students xmlns CDATA #FIXED ''>

<!ELEMENT img EMPTY>
<!ATTLIST img xmlns CDATA #FIXED '' src ENTITY #REQUIRED>

<!ELEMENT webSite (#PCDATA)>
<!ATTLIST webSite xmlns CDATA #FIXED '' href CDATA #REQUIRED>

<!ELEMENT faculty (#PCDATA)>
<!ATTLIST faculty xmlns CDATA #FIXED ''>

<!NOTATION jpg PUBLIC "image/jpg">
<!ENTITY su PUBLIC "images/1.jpg" '' NDATA jpg>
<!ENTITY tu PUBLIC "images/2.jpg" '' NDATA jpg>
<!ENTITY natfiz PUBLIC "images/3.jpg" '' NDATA jpg>
<!ENTITY amvr PUBLIC "images/4.jpg" '' NDATA jpg>
<!ENTITY vsuLK PUBLIC "images/5.jpg" '' NDATA jpg>
<!ENTITY vtu PUBLIC "images/6.jpg" '' NDATA jpg>
<!ENTITY vuzf PUBLIC "images/7.jpg" '' NDATA jpg>
<!ENTITY vutp PUBLIC "images/8.jpg" '' NDATA jpg>
<!ENTITY va PUBLIC "images/9.jpg" '' NDATA jpg>
<!ENTITY lu PUBLIC "images/10.jpg" '' NDATA jpg>
<!ENTITY mu PUBLIC "images/11.jpg" '' NDATA jpg>
<!ENTITY mgu PUBLIC "images/12.jpg" '' NDATA jpg>
<!ENTITY nma PUBLIC "images/13.jpg" '' NDATA jpg>
<!ENTITY nsa PUBLIC "images/14.jpg" '' NDATA jpg>
<!ENTITY nha PUBLIC "images/15.jpg" '' NDATA jpg>
<!ENTITY nbu PUBLIC "images/16.jpg" '' NDATA jpg>
<!ENTITY unss PUBLIC "images/17.jpg" '' NDATA jpg>
<!ENTITY uasg PUBLIC "images/18.jpg" '' NDATA jpg>
<!ENTITY unibit PUBLIC "images/19.jpg" '' NDATA jpg>
<!ENTITY htmu PUBLIC "images/20.jpg" '' NDATA jpg>
<!ENTITY aubg PUBLIC "images/21.jpg" '' NDATA jpg>
<!ENTITY uzu PUBLIC "images/22.jpg" '' NDATA jpg>
<!ENTITY bsu PUBLIC "images/23.jpg" '' NDATA jpg>
<!ENTITY vsu PUBLIC "images/24.jpg" '' NDATA jpg>
<!ENTITY vvu PUBLIC "images/25.jpg" '' NDATA jpg>
<!ENTITY vum PUBLIC "images/26.jpg" '' NDATA jpg>
<!ENTITY iu PUBLIC "images/27.jpg" '' NDATA jpg>
<!ENTITY muV PUBLIC "images/28.jpg" '' NDATA jpg>
<!ENTITY tuV PUBLIC "images/29.jpg" '' NDATA jpg>
<!ENTITY vtuKM PUBLIC "images/30.jpg" '' NDATA jpg>
<!ENTITY nvu PUBLIC "images/31.jpg" '' NDATA jpg>
<!ENTITY tuG PUBLIC "images/32.jpg" '' NDATA jpg>
<!ENTITY vvuGB PUBLIC "images/33.jpg" '' NDATA jpg>
<!ENTITY epu PUBLIC "images/34.jpg" '' NDATA jpg>
<!ENTITY muP PUBLIC "images/35.jpg" '' NDATA jpg>
<!ENTITY pu PUBLIC "images/36.jpg" '' NDATA jpg>
<!ENTITY au PUBLIC "images/37.jpg" '' NDATA jpg>
<!ENTITY amtii PUBLIC "images/38.jpg" '' NDATA jpg>
<!ENTITY vuarr PUBLIC "images/39.jpg" '' NDATA jpg>
<!ENTITY vusi PUBLIC "images/40.jpg" '' NDATA jpg>
<!ENTITY muPL PUBLIC "images/41.jpg" '' NDATA jpg>
<!ENTITY uht PUBLIC "images/42.jpg" '' NDATA jpg>
<!ENTITY ru PUBLIC "images/43.jpg" '' NDATA jpg>
<!ENTITY sa PUBLIC "images/44.jpg" '' NDATA jpg>
<!ENTITY tru PUBLIC "images/45.jpg" '' NDATA jpg>
<!ENTITY shu PUBLIC "images/46.jpg" '' NDATA jpg>
<!ENTITY muVr PUBLIC "images/111.jpg" '' NDATA jpg>
<!ENTITY tuP PUBLIC "images/201.jpg" '' NDATA jpg>
<!ENTITY tuS PUBLIC "images/202.jpg" '' NDATA jpg>
<!ENTITY muVT PUBLIC "images/281.jpg" '' NDATA jpg>
<!ENTITY muS PUBLIC "images/282.jpg" '' NDATA jpg>
<!ENTITY muSh PUBLIC "images/283.jpg" '' NDATA jpg>
<!ENTITY puS PUBLIC "images/361.jpg" '' NDATA jpg>
<!ENTITY puK PUBLIC "images/362.jpg" '' NDATA jpg>
<!ENTITY ruS PUBLIC "images/431.jpg" '' NDATA jpg>
<!ENTITY ruR PUBLIC "images/432.jpg" '' NDATA jpg>
<!ENTITY tuH PUBLIC "images/451.jpg" '' NDATA jpg>
<!ENTITY tuQ PUBLIC "images/452.jpg" '' NDATA jpg>
<!ENTITY shuD PUBLIC "images/461.jpg" '' NDATA jpg>

=== mariyaveleva16/XML/XML2022_ProjectNo8/universityCatalogue.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="universityCatalogueXslt.xsl"?>
<!DOCTYPE universitiesBG SYSTEM "unisInBG.dtd">
<universitiesBG  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="universityCatalogueScheme.xsd">
	<universityList>
		<university>
			<universityInfo>
				<name>Софийски университет "Св. Климент Охридски"</name>
				<location>София</location>
				<region>Югозападен регион</region>
				<id>1</id>
				<regionId>0206</regionId>
				<telephone>02/930-8200</telephone>
				<secondTelephone>02/946-0255</secondTelephone>
				<year>1888</year>
				<students>20516</students>
				<img src="su" />
				<webSite href="https://www.uni-sofia.bg/">www.uni-sofia.bg</webSite>
			</universityInfo>
			<facultyList>
				<faculty>Исторически факултет</faculty>
				<faculty>Философски факултет</faculty>
				<faculty>Факултет по класически и нови филологии</faculty>
				<faculty>Факултет по славянски филологии</faculty>
				<faculty>Юридически факултет</faculty>
				<faculty>Факултет по педагогика</faculty>
				<faculty>Факултет по науки за образованието и изкустата</faculty>
				<faculty>Факултет по журналистика и масова комуникация</faculty>
				<faculty>Богословски факултет</faculty>
				<faculty>Стопански факултет</faculty>
				<faculty>Факултет по математика и информатика</faculty>
				<faculty>Физически факултет</faculty>
				<faculty>Факултет по химия и фармация</faculty>
				<faculty>Биологически факултет</faculty>
				<faculty>Геолого-географски факултет</faculty>
				<faculty>Медицински факултет</faculty>
			</facultyList>
		</university>
		<university>
			<universityInfo>
				<name>Технически университет - София</name>
				<location>София</location>
				<region>Югозападен регион</region>
				<id>2</id>
				<regionId>0206</regionId>
				<telephone>02/862-3073</telephone>
				<secondTelephone>02/868-3215</secondTelephone>
				<year>1945</year>
				<students>11005</students>
				<img src="tu" />
				<webSite href="https://tu-sofia.bg/">www.tu-sofia.bg</webSite>
			</universityInfo>
			<facultyList>
				<faculty>Факултет по автоматика</faculty>
				<faculty>Електротехнически факултет</faculty>
				<faculty>Енергомашиностроителен факултет</faculty>
				<faculty>Машинно-технологичен факултет</faculty>
				<faculty>Машиностроителен факултет</faculty>
				<faculty>Факултет по електронна техника и технологии</faculty>
				<faculty>Факултет по телекомуникации</faculty>
				<faculty>Факултет по компютърни системи и технологии</faculty>
				<faculty>Факултет по транспорта</faculty>
				<faculty>Стопански факултет</faculty>
				<faculty>Факултет по приложна математика и информатика</faculty>
				<faculty>Факултет за германско инженерно обучение и промишленост</faculty>
				<faculty>Факултет за френско обучение по електроинженерство</faculty>
				<faculty>Факултет за английско инженерно обучение</faculty>
			</facultyList>
		</university>
		<university>
			<universityInfo>
				<name>Технически университет - София</name>
				<branchName>Филиал Пловдив</branchName>
				<location>Пловдив</location>
				<region>Южен централен регион</region>
				<id>201</id>
				<regionId>0205</regionId>
				<telephone>032/659-565</telephone>
				<year>1986</year>
				<img src="tuP" />
				<webSite href="http://www.tu-plovdiv.bg/">www.tu-plovdiv.bg</webSite>
			</universityInfo>
			<facultyList>
				<faculty>Факултет по електроника и автоматика</faculty>
				<faculty>Факултет по машиностроене и уредостроене</faculty>
			</facultyList>
		</university>
		<university>
			<universityInfo>
				<name>Технически университет - София</name>
				<branchName>Филиал Сливен</branchName>
				<location>Сливен</location>
				<region>Югоизточен регион</region>
				<id>202</id>
				<regionId>0204</regionId>
				<telephone>044/667-709</telephone>
				<secondTelephone>044/667-710</secondTelephone>
				<year>1983</year>
				<img src="tuS" />
				<webSite href="http://www.tu-sliven.com/">www.tu-sliven.com</webSite>
			</universityInfo>
			<facultyList>
				<faculty>Инженерно-педагогически факултет</faculty>
			</facultyList>
		</university>
		<university>
			<universityInfo>
				<name>Национална академия за театрално и филмово изкуство "Кръстьо Сарафов"</name>
				<location>София</location>
				<region>Югозападен регион</region>
				<id>3</id>
				<regionId>0206</regionId>
				<telephone>02/923-1225</telephone>
				<year>1948</year>
				<students>628</students>
				<img src="natfiz" />
				<webSite href="http://natfiz.bg/">www.natfiz.bg</webSite>
			</universityInfo>
			<facultyList>
				<faculty>Факултет "Сценични изкуства"</faculty>
				<faculty>Факултет "Екранни изкуства"</faculty>
			</facultyList>
		</university>
		<university>
			<universityInfo>
				<name>Академия на Министерството на вътрешните работи - София</name>
				<location>София</location>
				<region>Югозападен регион</region>
				<id>4</id>
				<regionId>0206</regionId>
				<telephone>9829250</telephone>
				<secondTelephone>9743785</secondTelephone>
				<year>2002</year>
				<students>1572</students>
				<img src="amvr" />
				<webSite href="https://www.mvr.bg/academy">www.mvr.bg/academy</webSite>
			</universityInfo>
			<facultyList>
				<faculty>Факултет "Полиция"</faculty>
				<faculty>Факултет "Пожрна безопасност и защита на населението"</faculty>
			</facultyList>
		</university>
		<university>
			<universityInfo>
				<name>Висше строително училище "Любен Каравелов" - София</name>
				<location>София</location>
				<region>Югозападен регион</region>
				<id>5</id>
				<regionId>0206</regionId>
				<telephone>8029100</telephone>
				<secondTelephone>8029101</secondTelephone>
				<year>1938</year>
				<students>587</students>
				<img src="vsuLK" />
				<webSite href="https://www.vsu.bg">www.vsu.bg</webSite>
			</universityInfo>
			<facultyList>
				<faculty>Строителен факултет</faculty>
				<faculty>Архитектурен факултет</faculty>
			</facultyList>
		</university>
		<university>
			<universityInfo>
				<name>Висше транспортно училище "Тодор Каблешков" - София</name>
				<location>София</location>
				<region>Югозападен регион</region>
				<id>6</id>
				<regionId>0206</regionId>
				<telephone>9709478</telephone>
				<secondTelephone>970928242</secondTelephone>
				<year>1922</year>
				<students>1466</students>
				<img src="vtu" />
				<webSite href="https://www.vtu.bg">www.vtu.bg</webSite>
			</universityInfo>
			<facultyList>
				<faculty>Факултет Транспортен мениджмънт</faculty>
				<faculty>Факултет Комуникации и електрообзавеждане в транспорта</faculty>
				<faculty>Факултет Техника и строителни технологии в транспорта</faculty>
			</facultyList>
		</university>
		<university>
			<universityInfo>
				<name>Висше училище по застраховане и финанси - София</name>
				<location>София</location>
				<region>Югозападен регион</region>
				<id>7</id>
				<regionId>0206</regionId>
				<telephone>4015811</telephone>
				<year>2000</year>
				<students>1664</students>
				<img src="vuzf" />
				<webSite href="https://www.vuzf.bg">www.vuzf.bg</webSite>
			</universityInfo>
			<facultyList>
				<faculty>Факултет по финанси</faculty>
				<faculty>Факултет по застраховане и осигуряване</faculty>
				<faculty>Факултет по счетоводство и контрол</faculty>
				<faculty>Факултет по маркетинг и мениджмънт</faculty>
			</facultyList>
		</university>
		<university>
			<universityInfo>
				<name>Висше училище по телекомуникации и пощи - София</name>
				<location>София</location>
				<region>Югозападен регион</region>
				<id>8</id>
				<regionId>0206</regionId>
				<telephone>02/862-1034</telephone>
				<secondTelephone>02/806-2227</secondTelephone>
				<year>1923</year>
				<students>1624</students>
				<img src="vutp" />
				<webSite href="https://www.utp.bg">www.utp.bg</webSite>
			</universityInfo>
			<facultyList>
				<faculty>Факултет "Телекомуникации"</faculty>
				<faculty>Факултет "Информационни технологии"</faculty>
				<faculty>Факултет "Мениджмънт в съобщенията"</faculty>
			</facultyList>
		</university>
		<university>
			<universityInfo>
				<name>Военна академия "Георги Стойков Раковски" - София</name>
				<location>София</location>
				<region>Югозападен регион</region>
				<id>9</id>
				<regionId>0206</regionId>
				<telephone>02/922-6500</telephone>
				<secondTelephone>02/944-1657</secondTelephone>
				<year>1912</year>
				<students>1643</students>
				<img src="va" />
				<webSite href="https://rndc.bg">rndc.bg</webSite>
			</universityInfo>
			<facultyList>
				<faculty>Факултет "Национална сигурност и отбрана"</faculty>
				<faculty>Факултет "Командно-щабен"</faculty>
			</facultyList>
		</university>
		<university>
			<universityInfo>
				<name>Лесотехнически университет - София</name>
				<location>София</location>
				<region>Югозападен регион</region>
				<id>10</id>
				<regionId>0206</regionId>
				<telephone>02/962-5997</telephone>
				<secondTelephone>02/868-2830</secondTelephone>
				<year>1953</year>
				<students>2787</students>
				<img src="lu" />
				<webSite href="https://www.ltu.bg">www.ltu.bg</webSite>
			</universityInfo>
			<facultyList>
				<faculty>Факултет "Горско стопанство"</faculty>
				<faculty>Факултет "Горска промишленост"</faculty>
				<faculty>Факултет "Екология и лантшафтна архитектура"</faculty>
				<faculty>Факултет "Стопанско управление"</faculty>
				<faculty>Факултет "Ветеринарна медицина"</faculty>
				<faculty>Агрономически факултет</faculty>
			</facultyList>
		</university>
		<university>
			<universityInfo>
				<name>Медицински университет - София</name>
				<location>София</location>
				<region>Югозападен регион</region>
				<id>11</id>
				<regionId>0206</regionId>
